const SOURATES = [
  { numero: 1, nomArabe: 'الفاتحة', nomFr: 'Al-Fatiha', nombreVersets: 7, nombrePages: 0.5 },
  { numero: 2, nomArabe: 'البقرة', nomFr: 'Al-Baqara', nombreVersets: 286, nombrePages: 48.5 },
  { numero: 3, nomArabe: 'آل عمران', nomFr: 'Ali Imran', nombreVersets: 200, nombrePages: 29 },
  { numero: 4, nomArabe: 'النساء', nomFr: 'An-Nisa', nombreVersets: 176, nombrePages: 29 },
  { numero: 5, nomArabe: 'المائدة', nomFr: 'Al-Maida', nombreVersets: 120, nombrePages: 22 },
  { numero: 6, nomArabe: 'الأنعام', nomFr: 'Al-Anam', nombreVersets: 165, nombrePages: 20.5 },
  { numero: 7, nomArabe: 'الأعراف', nomFr: 'Al-Araf', nombreVersets: 206, nombrePages: 24 },
  { numero: 8, nomArabe: 'الأنفال', nomFr: 'Al-Anfal', nombreVersets: 75, nombrePages: 9.5 },
  { numero: 9, nomArabe: 'التوبة', nomFr: 'At-Tawba', nombreVersets: 129, nombrePages: 19 },
  { numero: 10, nomArabe: 'يونس', nomFr: 'Yunus', nombreVersets: 109, nombrePages: 11 },
  { numero: 11, nomArabe: 'هود', nomFr: 'Hud', nombreVersets: 123, nombrePages: 10.5 },
  { numero: 12, nomArabe: 'يوسف', nomFr: 'Yusuf', nombreVersets: 111, nombrePages: 11 },
  { numero: 13, nomArabe: 'الرعد', nomFr: 'Ar-Rad', nombreVersets: 43, nombrePages: 6 },
  { numero: 14, nomArabe: 'إبراهيم', nomFr: 'Ibrahim', nombreVersets: 52, nombrePages: 6 },
  { numero: 15, nomArabe: 'الحجر', nomFr: 'Al-Hijr', nombreVersets: 99, nombrePages: 6 },
  { numero: 16, nomArabe: 'النحل', nomFr: 'An-Nahl', nombreVersets: 128, nombrePages: 11 },
  { numero: 17, nomArabe: 'الإسراء', nomFr: 'Al-Isra', nombreVersets: 111, nombrePages: 12 },
  { numero: 18, nomArabe: 'الكهف', nomFr: 'Al-Kahf', nombreVersets: 110, nombrePages: 11 },
  { numero: 19, nomArabe: 'مريم', nomFr: 'Maryam', nombreVersets: 98, nombrePages: 8 },
  { numero: 20, nomArabe: 'طه', nomFr: 'Ta-Ha', nombreVersets: 135, nombrePages: 8 },
  { numero: 21, nomArabe: 'الأنبياء', nomFr: 'Al-Anbiya', nombreVersets: 112, nombrePages: 11.5 },
  { numero: 22, nomArabe: 'الحج', nomFr: 'Al-Hajj', nombreVersets: 78, nombrePages: 10 },
  { numero: 23, nomArabe: 'المؤمنون', nomFr: 'Al-Muminun', nombreVersets: 118, nombrePages: 9 },
  { numero: 24, nomArabe: 'النور', nomFr: 'An-Nur', nombreVersets: 64, nombrePages: 9 },
  { numero: 25, nomArabe: 'الفرقان', nomFr: 'Al-Furqan', nombreVersets: 77, nombrePages: 7.5 },
  { numero: 26, nomArabe: 'الشعراء', nomFr: 'Ash-Shuara', nombreVersets: 227, nombrePages: 11 },
  { numero: 27, nomArabe: 'النمل', nomFr: 'An-Naml', nombreVersets: 93, nombrePages: 9.5 },
  { numero: 28, nomArabe: 'القصص', nomFr: 'Al-Qasas', nombreVersets: 88, nombrePages: 9.5 },
  { numero: 29, nomArabe: 'العنكبوت', nomFr: 'Al-Ankabut', nombreVersets: 69, nombrePages: 7 },
  { numero: 30, nomArabe: 'الروم', nomFr: 'Ar-Rum', nombreVersets: 60, nombrePages: 6 },
  { numero: 31, nomArabe: 'لقمان', nomFr: 'Luqman', nombreVersets: 34, nombrePages: 4 },
  { numero: 32, nomArabe: 'السجدة', nomFr: 'As-Sajda', nombreVersets: 30, nombrePages: 3 },
  { numero: 33, nomArabe: 'الأحزاب', nomFr: 'Al-Ahzab', nombreVersets: 73, nombrePages: 9 },
  { numero: 34, nomArabe: 'سبأ', nomFr: 'Saba', nombreVersets: 54, nombrePages: 6 },
  { numero: 35, nomArabe: 'فاطر', nomFr: 'Fatir', nombreVersets: 45, nombrePages: 5.5 },
  { numero: 36, nomArabe: 'يس', nomFr: 'Ya-Sin', nombreVersets: 83, nombrePages: 4.5 },
  { numero: 37, nomArabe: 'الصافات', nomFr: 'As-Saffat', nombreVersets: 182, nombrePages: 11 },
  { numero: 38, nomArabe: 'ص', nomFr: 'Sad', nombreVersets: 88, nombrePages: 7 },
  { numero: 39, nomArabe: 'الزمر', nomFr: 'Az-Zumar', nombreVersets: 75, nombrePages: 8 },
  { numero: 40, nomArabe: 'غافر', nomFr: 'Ghafir', nombreVersets: 85, nombrePages: 9 },
  { numero: 41, nomArabe: 'فصلت', nomFr: 'Fussilat', nombreVersets: 54, nombrePages: 7.5 },
  { numero: 42, nomArabe: 'الشورى', nomFr: 'Ash-Shura', nombreVersets: 53, nombrePages: 7 },
  { numero: 43, nomArabe: 'الزخرف', nomFr: 'Az-Zukhruf', nombreVersets: 89, nombrePages: 7.5 },
  { numero: 44, nomArabe: 'الدخان', nomFr: 'Ad-Dukhan', nombreVersets: 59, nombrePages: 3.5 },
  { numero: 45, nomArabe: 'الجاثية', nomFr: 'Al-Jathiya', nombreVersets: 37, nombrePages: 4 },
  { numero: 46, nomArabe: 'الأحقاف', nomFr: 'Al-Ahqaf', nombreVersets: 35, nombrePages: 4.5 },
  { numero: 47, nomArabe: 'محمد', nomFr: 'Muhammad', nombreVersets: 38, nombrePages: 4.5 },
  { numero: 48, nomArabe: 'الفتح', nomFr: 'Al-Fath', nombreVersets: 29, nombrePages: 4.5 },
  { numero: 49, nomArabe: 'الحجرات', nomFr: 'Al-Hujurat', nombreVersets: 18, nombrePages: 2 },
  { numero: 50, nomArabe: 'ق', nomFr: 'Qaf', nombreVersets: 45, nombrePages: 3 },
  { numero: 51, nomArabe: 'الذاريات', nomFr: 'Adh-Dhariyat', nombreVersets: 60, nombrePages: 3 },
  { numero: 52, nomArabe: 'الطور', nomFr: 'At-Tur', nombreVersets: 49, nombrePages: 3 },
  { numero: 53, nomArabe: 'النجم', nomFr: 'An-Najm', nombreVersets: 62, nombrePages: 3 },
  { numero: 54, nomArabe: 'القمر', nomFr: 'Al-Qamar', nombreVersets: 55, nombrePages: 3 },
  { numero: 55, nomArabe: 'الرحمن', nomFr: 'Ar-Rahman', nombreVersets: 78, nombrePages: 3.5 },
  { numero: 56, nomArabe: 'الواقعة', nomFr: 'Al-Waqia', nombreVersets: 96, nombrePages: 3.5 },
  { numero: 57, nomArabe: 'الحديد', nomFr: 'Al-Hadid', nombreVersets: 29, nombrePages: 4.5 },
  { numero: 58, nomArabe: 'المجادلة', nomFr: 'Al-Mujadila', nombreVersets: 22, nombrePages: 3 },
  { numero: 59, nomArabe: 'الحشر', nomFr: 'Al-Hashr', nombreVersets: 24, nombrePages: 3 },
  { numero: 60, nomArabe: 'الممتحنة', nomFr: 'Al-Mumtahana', nombreVersets: 13, nombrePages: 2.5 },
  { numero: 61, nomArabe: 'الصف', nomFr: 'As-Saf', nombreVersets: 14, nombrePages: 2 },
  { numero: 62, nomArabe: 'الجمعة', nomFr: 'Al-Jumua', nombreVersets: 11, nombrePages: 1.5 },
  { numero: 63, nomArabe: 'المنافقون', nomFr: 'Al-Munafiqun', nombreVersets: 11, nombrePages: 1.5 },
  { numero: 64, nomArabe: 'التغابن', nomFr: 'At-Taghabun', nombreVersets: 18, nombrePages: 2 },
  { numero: 65, nomArabe: 'الطلاق', nomFr: 'At-Talaq', nombreVersets: 12, nombrePages: 2 },
  { numero: 66, nomArabe: 'التحريم', nomFr: 'At-Tahrim', nombreVersets: 12, nombrePages: 2 },
  { numero: 67, nomArabe: 'الملك', nomFr: 'Al-Mulk', nombreVersets: 30, nombrePages: 2.5 },
  { numero: 68, nomArabe: 'القلم', nomFr: 'Al-Qalam', nombreVersets: 52, nombrePages: 2.5 },
  { numero: 69, nomArabe: 'الحاقة', nomFr: 'Al-Haqqa', nombreVersets: 52, nombrePages: 2 },
  { numero: 70, nomArabe: 'المعارج', nomFr: 'Al-Maarij', nombreVersets: 44, nombrePages: 2 },
  { numero: 71, nomArabe: 'نوح', nomFr: 'Nuh', nombreVersets: 28, nombrePages: 1.5 },
  { numero: 72, nomArabe: 'الجن', nomFr: 'Al-Jinn', nombreVersets: 28, nombrePages: 2 },
  { numero: 73, nomArabe: 'المزمل', nomFr: 'Al-Muzzammil', nombreVersets: 20, nombrePages: 1.5 },
  { numero: 74, nomArabe: 'المدثر', nomFr: 'Al-Muddaththir', nombreVersets: 56, nombrePages: 2 },
  { numero: 75, nomArabe: 'القيامة', nomFr: 'Al-Qiyama', nombreVersets: 40, nombrePages: 1.5 },
  { numero: 76, nomArabe: 'الإنسان', nomFr: 'Al-Insan', nombreVersets: 31, nombrePages: 2 },
  { numero: 77, nomArabe: 'المرسلات', nomFr: 'Al-Mursalat', nombreVersets: 50, nombrePages: 1.5 },
  { numero: 78, nomArabe: 'النبأ', nomFr: 'An-Naba', nombreVersets: 40, nombrePages: 1.5 },
  { numero: 79, nomArabe: 'النازعات', nomFr: 'An-Naziat', nombreVersets: 46, nombrePages: 1.5 },
  { numero: 80, nomArabe: 'عبس', nomFr: 'Abasa', nombreVersets: 42, nombrePages: 1 },
  { numero: 81, nomArabe: 'التكوير', nomFr: 'At-Takwir', nombreVersets: 29, nombrePages: 1 },
  { numero: 82, nomArabe: 'الانفطار', nomFr: 'Al-Infitar', nombreVersets: 19, nombrePages: 0.5 },
  { numero: 83, nomArabe: 'المطففين', nomFr: 'Al-Mutaffifin', nombreVersets: 36, nombrePages: 1.5 },
  { numero: 84, nomArabe: 'الانشقاق', nomFr: 'Al-Inshiqaq', nombreVersets: 25, nombrePages: 0.5 },
  { numero: 85, nomArabe: 'البروج', nomFr: 'Al-Buruj', nombreVersets: 22, nombrePages: 0.5 },
  { numero: 86, nomArabe: 'الطارق', nomFr: 'At-Tariq', nombreVersets: 17, nombrePages: 0.5 },
  { numero: 87, nomArabe: 'الأعلى', nomFr: 'Al-Ala', nombreVersets: 19, nombrePages: 0.5 },
  { numero: 88, nomArabe: 'الغاشية', nomFr: 'Al-Ghashiya', nombreVersets: 26, nombrePages: 0.5 },
  { numero: 89, nomArabe: 'الفجر', nomFr: 'Al-Fajr', nombreVersets: 30, nombrePages: 1 },
  { numero: 90, nomArabe: 'البلد', nomFr: 'Al-Balad', nombreVersets: 20, nombrePages: 0.5 },
  { numero: 91, nomArabe: 'الشمس', nomFr: 'Ash-Shams', nombreVersets: 15, nombrePages: 0.5 },
  { numero: 92, nomArabe: 'الليل', nomFr: 'Al-Layl', nombreVersets: 21, nombrePages: 0.5 },
  { numero: 93, nomArabe: 'الضحى', nomFr: 'Ad-Duha', nombreVersets: 11, nombrePages: 0.5 },
  { numero: 94, nomArabe: 'الشرح', nomFr: 'Ash-Sharh', nombreVersets: 8, nombrePages: 0.25 },
  { numero: 95, nomArabe: 'التين', nomFr: 'At-Tin', nombreVersets: 8, nombrePages: 0.25 },
  { numero: 96, nomArabe: 'العلق', nomFr: 'Al-Alaq', nombreVersets: 19, nombrePages: 0.5 },
  { numero: 97, nomArabe: 'القدر', nomFr: 'Al-Qadr', nombreVersets: 5, nombrePages: 0.25 },
  { numero: 98, nomArabe: 'البينة', nomFr: 'Al-Bayyina', nombreVersets: 8, nombrePages: 0.5 },
  { numero: 99, nomArabe: 'الزلزلة', nomFr: 'Az-Zalzala', nombreVersets: 8, nombrePages: 0.25 },
  { numero: 100, nomArabe: 'العاديات', nomFr: 'Al-Adiyat', nombreVersets: 11, nombrePages: 0.25 },
  { numero: 101, nomArabe: 'القارعة', nomFr: 'Al-Qaria', nombreVersets: 11, nombrePages: 0.25 },
  { numero: 102, nomArabe: 'التكاثر', nomFr: 'At-Takathur', nombreVersets: 8, nombrePages: 0.25 },
  { numero: 103, nomArabe: 'العصر', nomFr: 'Al-Asr', nombreVersets: 3, nombrePages: 0.25 },
  { numero: 104, nomArabe: 'الهمزة', nomFr: 'Al-Humaza', nombreVersets: 9, nombrePages: 0.25 },
  { numero: 105, nomArabe: 'الفيل', nomFr: 'Al-Fil', nombreVersets: 5, nombrePages: 0.25 },
  { numero: 106, nomArabe: 'قريش', nomFr: 'Quraysh', nombreVersets: 4, nombrePages: 0.25 },
  { numero: 107, nomArabe: 'الماعون', nomFr: 'Al-Maun', nombreVersets: 7, nombrePages: 0.25 },
  { numero: 108, nomArabe: 'الكوثر', nomFr: 'Al-Kawthar', nombreVersets: 3, nombrePages: 0.25 },
  { numero: 109, nomArabe: 'الكافرون', nomFr: 'Al-Kafirun', nombreVersets: 6, nombrePages: 0.25 },
  { numero: 110, nomArabe: 'النصر', nomFr: 'An-Nasr', nombreVersets: 3, nombrePages: 0.25 },
  { numero: 111, nomArabe: 'المسد', nomFr: 'Al-Masad', nombreVersets: 5, nombrePages: 0.25 },
  { numero: 112, nomArabe: 'الإخلاص', nomFr: 'Al-Ikhlas', nombreVersets: 4, nombrePages: 0.25 },
  { numero: 113, nomArabe: 'الفلق', nomFr: 'Al-Falaq', nombreVersets: 5, nombrePages: 0.25 },
  { numero: 114, nomArabe: 'الناس', nomFr: 'An-Nas', nombreVersets: 6, nombrePages: 0.25 },
];

async function upsertSourates(prisma) {
  for (const sourate of SOURATES) {
    await prisma.sourateCoran.upsert({
      where: { numero: sourate.numero },
      update: sourate,
      create: sourate,
    });
  }
  return SOURATES.length;
}

module.exports = { SOURATES, upsertSourates };
