-- Peuple la table sourates_coran avec les 114 sourates (données de référence,
-- requises pour le module Suivi Coran). Ce contenu était jusqu'ici uniquement inséré
-- par prisma/seed.js — un script à part, jamais exécuté en production (car il crée
-- aussi des comptes de démo), d'où une liste de sourates vide en prod alors qu'elle
-- était peuplée en local par ce même script. Migration = appliquée automatiquement
-- partout via 'prisma migrate deploy', sans dépendre du seed de démo.
-- Idempotent (ON CONFLICT) : sans effet si déjà peuplée (ex: en local).

INSERT INTO "sourates_coran" ("id", "numero", "nom_arabe", "nom_fr", "nombre_versets", "nombre_pages")
VALUES
  (gen_random_uuid()::text, 1, 'الفاتحة', 'Al-Fatiha', 7, 0.5),
  (gen_random_uuid()::text, 2, 'البقرة', 'Al-Baqara', 286, 48.5),
  (gen_random_uuid()::text, 3, 'آل عمران', 'Ali Imran', 200, 29),
  (gen_random_uuid()::text, 4, 'النساء', 'An-Nisa', 176, 29),
  (gen_random_uuid()::text, 5, 'المائدة', 'Al-Maida', 120, 22),
  (gen_random_uuid()::text, 6, 'الأنعام', 'Al-Anam', 165, 20.5),
  (gen_random_uuid()::text, 7, 'الأعراف', 'Al-Araf', 206, 24),
  (gen_random_uuid()::text, 8, 'الأنفال', 'Al-Anfal', 75, 9.5),
  (gen_random_uuid()::text, 9, 'التوبة', 'At-Tawba', 129, 19),
  (gen_random_uuid()::text, 10, 'يونس', 'Yunus', 109, 11),
  (gen_random_uuid()::text, 11, 'هود', 'Hud', 123, 10.5),
  (gen_random_uuid()::text, 12, 'يوسف', 'Yusuf', 111, 11),
  (gen_random_uuid()::text, 13, 'الرعد', 'Ar-Rad', 43, 6),
  (gen_random_uuid()::text, 14, 'إبراهيم', 'Ibrahim', 52, 6),
  (gen_random_uuid()::text, 15, 'الحجر', 'Al-Hijr', 99, 6),
  (gen_random_uuid()::text, 16, 'النحل', 'An-Nahl', 128, 11),
  (gen_random_uuid()::text, 17, 'الإسراء', 'Al-Isra', 111, 12),
  (gen_random_uuid()::text, 18, 'الكهف', 'Al-Kahf', 110, 11),
  (gen_random_uuid()::text, 19, 'مريم', 'Maryam', 98, 8),
  (gen_random_uuid()::text, 20, 'طه', 'Ta-Ha', 135, 8),
  (gen_random_uuid()::text, 21, 'الأنبياء', 'Al-Anbiya', 112, 11.5),
  (gen_random_uuid()::text, 22, 'الحج', 'Al-Hajj', 78, 10),
  (gen_random_uuid()::text, 23, 'المؤمنون', 'Al-Muminun', 118, 9),
  (gen_random_uuid()::text, 24, 'النور', 'An-Nur', 64, 9),
  (gen_random_uuid()::text, 25, 'الفرقان', 'Al-Furqan', 77, 7.5),
  (gen_random_uuid()::text, 26, 'الشعراء', 'Ash-Shuara', 227, 11),
  (gen_random_uuid()::text, 27, 'النمل', 'An-Naml', 93, 9.5),
  (gen_random_uuid()::text, 28, 'القصص', 'Al-Qasas', 88, 9.5),
  (gen_random_uuid()::text, 29, 'العنكبوت', 'Al-Ankabut', 69, 7),
  (gen_random_uuid()::text, 30, 'الروم', 'Ar-Rum', 60, 6),
  (gen_random_uuid()::text, 31, 'لقمان', 'Luqman', 34, 4),
  (gen_random_uuid()::text, 32, 'السجدة', 'As-Sajda', 30, 3),
  (gen_random_uuid()::text, 33, 'الأحزاب', 'Al-Ahzab', 73, 9),
  (gen_random_uuid()::text, 34, 'سبأ', 'Saba', 54, 6),
  (gen_random_uuid()::text, 35, 'فاطر', 'Fatir', 45, 5.5),
  (gen_random_uuid()::text, 36, 'يس', 'Ya-Sin', 83, 4.5),
  (gen_random_uuid()::text, 37, 'الصافات', 'As-Saffat', 182, 11),
  (gen_random_uuid()::text, 38, 'ص', 'Sad', 88, 7),
  (gen_random_uuid()::text, 39, 'الزمر', 'Az-Zumar', 75, 8),
  (gen_random_uuid()::text, 40, 'غافر', 'Ghafir', 85, 9),
  (gen_random_uuid()::text, 41, 'فصلت', 'Fussilat', 54, 7.5),
  (gen_random_uuid()::text, 42, 'الشورى', 'Ash-Shura', 53, 7),
  (gen_random_uuid()::text, 43, 'الزخرف', 'Az-Zukhruf', 89, 7.5),
  (gen_random_uuid()::text, 44, 'الدخان', 'Ad-Dukhan', 59, 3.5),
  (gen_random_uuid()::text, 45, 'الجاثية', 'Al-Jathiya', 37, 4),
  (gen_random_uuid()::text, 46, 'الأحقاف', 'Al-Ahqaf', 35, 4.5),
  (gen_random_uuid()::text, 47, 'محمد', 'Muhammad', 38, 4.5),
  (gen_random_uuid()::text, 48, 'الفتح', 'Al-Fath', 29, 4.5),
  (gen_random_uuid()::text, 49, 'الحجرات', 'Al-Hujurat', 18, 2),
  (gen_random_uuid()::text, 50, 'ق', 'Qaf', 45, 3),
  (gen_random_uuid()::text, 51, 'الذاريات', 'Adh-Dhariyat', 60, 3),
  (gen_random_uuid()::text, 52, 'الطور', 'At-Tur', 49, 3),
  (gen_random_uuid()::text, 53, 'النجم', 'An-Najm', 62, 3),
  (gen_random_uuid()::text, 54, 'القمر', 'Al-Qamar', 55, 3),
  (gen_random_uuid()::text, 55, 'الرحمن', 'Ar-Rahman', 78, 3.5),
  (gen_random_uuid()::text, 56, 'الواقعة', 'Al-Waqia', 96, 3.5),
  (gen_random_uuid()::text, 57, 'الحديد', 'Al-Hadid', 29, 4.5),
  (gen_random_uuid()::text, 58, 'المجادلة', 'Al-Mujadila', 22, 3),
  (gen_random_uuid()::text, 59, 'الحشر', 'Al-Hashr', 24, 3),
  (gen_random_uuid()::text, 60, 'الممتحنة', 'Al-Mumtahana', 13, 2.5),
  (gen_random_uuid()::text, 61, 'الصف', 'As-Saf', 14, 2),
  (gen_random_uuid()::text, 62, 'الجمعة', 'Al-Jumua', 11, 1.5),
  (gen_random_uuid()::text, 63, 'المنافقون', 'Al-Munafiqun', 11, 1.5),
  (gen_random_uuid()::text, 64, 'التغابن', 'At-Taghabun', 18, 2),
  (gen_random_uuid()::text, 65, 'الطلاق', 'At-Talaq', 12, 2),
  (gen_random_uuid()::text, 66, 'التحريم', 'At-Tahrim', 12, 2),
  (gen_random_uuid()::text, 67, 'الملك', 'Al-Mulk', 30, 2.5),
  (gen_random_uuid()::text, 68, 'القلم', 'Al-Qalam', 52, 2.5),
  (gen_random_uuid()::text, 69, 'الحاقة', 'Al-Haqqa', 52, 2),
  (gen_random_uuid()::text, 70, 'المعارج', 'Al-Maarij', 44, 2),
  (gen_random_uuid()::text, 71, 'نوح', 'Nuh', 28, 1.5),
  (gen_random_uuid()::text, 72, 'الجن', 'Al-Jinn', 28, 2),
  (gen_random_uuid()::text, 73, 'المزمل', 'Al-Muzzammil', 20, 1.5),
  (gen_random_uuid()::text, 74, 'المدثر', 'Al-Muddaththir', 56, 2),
  (gen_random_uuid()::text, 75, 'القيامة', 'Al-Qiyama', 40, 1.5),
  (gen_random_uuid()::text, 76, 'الإنسان', 'Al-Insan', 31, 2),
  (gen_random_uuid()::text, 77, 'المرسلات', 'Al-Mursalat', 50, 1.5),
  (gen_random_uuid()::text, 78, 'النبأ', 'An-Naba', 40, 1.5),
  (gen_random_uuid()::text, 79, 'النازعات', 'An-Naziat', 46, 1.5),
  (gen_random_uuid()::text, 80, 'عبس', 'Abasa', 42, 1),
  (gen_random_uuid()::text, 81, 'التكوير', 'At-Takwir', 29, 1),
  (gen_random_uuid()::text, 82, 'الانفطار', 'Al-Infitar', 19, 0.5),
  (gen_random_uuid()::text, 83, 'المطففين', 'Al-Mutaffifin', 36, 1.5),
  (gen_random_uuid()::text, 84, 'الانشقاق', 'Al-Inshiqaq', 25, 0.5),
  (gen_random_uuid()::text, 85, 'البروج', 'Al-Buruj', 22, 0.5),
  (gen_random_uuid()::text, 86, 'الطارق', 'At-Tariq', 17, 0.5),
  (gen_random_uuid()::text, 87, 'الأعلى', 'Al-Ala', 19, 0.5),
  (gen_random_uuid()::text, 88, 'الغاشية', 'Al-Ghashiya', 26, 0.5),
  (gen_random_uuid()::text, 89, 'الفجر', 'Al-Fajr', 30, 1),
  (gen_random_uuid()::text, 90, 'البلد', 'Al-Balad', 20, 0.5),
  (gen_random_uuid()::text, 91, 'الشمس', 'Ash-Shams', 15, 0.5),
  (gen_random_uuid()::text, 92, 'الليل', 'Al-Layl', 21, 0.5),
  (gen_random_uuid()::text, 93, 'الضحى', 'Ad-Duha', 11, 0.5),
  (gen_random_uuid()::text, 94, 'الشرح', 'Ash-Sharh', 8, 0.25),
  (gen_random_uuid()::text, 95, 'التين', 'At-Tin', 8, 0.25),
  (gen_random_uuid()::text, 96, 'العلق', 'Al-Alaq', 19, 0.5),
  (gen_random_uuid()::text, 97, 'القدر', 'Al-Qadr', 5, 0.25),
  (gen_random_uuid()::text, 98, 'البينة', 'Al-Bayyina', 8, 0.5),
  (gen_random_uuid()::text, 99, 'الزلزلة', 'Az-Zalzala', 8, 0.25),
  (gen_random_uuid()::text, 100, 'العاديات', 'Al-Adiyat', 11, 0.25),
  (gen_random_uuid()::text, 101, 'القارعة', 'Al-Qaria', 11, 0.25),
  (gen_random_uuid()::text, 102, 'التكاثر', 'At-Takathur', 8, 0.25),
  (gen_random_uuid()::text, 103, 'العصر', 'Al-Asr', 3, 0.25),
  (gen_random_uuid()::text, 104, 'الهمزة', 'Al-Humaza', 9, 0.25),
  (gen_random_uuid()::text, 105, 'الفيل', 'Al-Fil', 5, 0.25),
  (gen_random_uuid()::text, 106, 'قريش', 'Quraysh', 4, 0.25),
  (gen_random_uuid()::text, 107, 'الماعون', 'Al-Maun', 7, 0.25),
  (gen_random_uuid()::text, 108, 'الكوثر', 'Al-Kawthar', 3, 0.25),
  (gen_random_uuid()::text, 109, 'الكافرون', 'Al-Kafirun', 6, 0.25),
  (gen_random_uuid()::text, 110, 'النصر', 'An-Nasr', 3, 0.25),
  (gen_random_uuid()::text, 111, 'المسد', 'Al-Masad', 5, 0.25),
  (gen_random_uuid()::text, 112, 'الإخلاص', 'Al-Ikhlas', 4, 0.25),
  (gen_random_uuid()::text, 113, 'الفلق', 'Al-Falaq', 5, 0.25),
  (gen_random_uuid()::text, 114, 'الناس', 'An-Nas', 6, 0.25)
ON CONFLICT ("numero") DO UPDATE SET
  "nom_arabe" = EXCLUDED."nom_arabe",
  "nom_fr" = EXCLUDED."nom_fr",
  "nombre_versets" = EXCLUDED."nombre_versets",
  "nombre_pages" = EXCLUDED."nombre_pages";
